version: 2

seeds:
  - name: dept19_update_nouveau_pt
    description: >
      Affectation manuelle de nouveau comptages vers des lignes BdTopo dans le dept 19
      milléisme 2024.
      les champs id_ign et id_simpli sont exclusifs : si l'un est renseigné, l'autre doit être null ; 
      si plusieurs lignes sont concernées, elles doivent etre séparées par des ';'.
    data_tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "(id_ign is not null and id_simpli is null) or (id_ign is null and id_simpli is not null)"
            description: "Vérifier que id_ign et id_simpli sont mutuellement exclusifs : si l'un est non null, l'autre doit être null."
    config:
      column_types:
        id_comptag: varchar(254)
        id_ign: text
        id_simpli: text
        src_cpt: varchar(254)
        coment_cpt: varchar(254)
        coment_tmj_f: varchar(254)
        obs_tmja: varchar(254)
        obs_pc_pl: varchar(254)
        obs_supl: varchar(254)
        id_sect: varchar(254)
        src_sect: varchar(254)
        autor_sect: varchar(254)
        obs_vts: varchar(254)
        id_cpt1: varchar(254)

    columns:
      - name: id_comptag
        description: "Identifiant du compteur"
        data_tests:
          - not_null
          - unique
      - name: id_ign
        description: "Identifiant IGN du(es) tronçon BdTopo linéarisé (séparation par ';' si plusieurs tronçons)"
      - name: id_simpli
        description: "Identifiant de section homogène interne OTR (séparation par ';' si plusieurs tronçons)"
      - name: src_cpt
        description: "source du comptage ; n'accepte que otv"
        data_tests:
          - accepted_values:
              arguments:
                values: "{{ var('src_cpt_verif') }}"
      - name: coment_cpt
        description: "Commentaire sur le comptage (linearisation, estimation)"
        data_tests:
          - accepted_values:
              arguments:
                values: "{{ var('coment_cpt_verif') }}"
      - name: coment_tmj_f
        description: "Commentaire sur le mode de calcul du tmja et le nombre de ligne qui représente la route"
        data_tests:
          - accepted_values:
              arguments:
                values: "{{ var('coment_tmj_verif') }}"
      - name: obs_tmja
        description: "Observation sur le TMJA"
      - name: obs_pc_pl
        description: "Observation sur la part de PL"
      - name: obs_supl
        description: "Observation supplémentaire"
      - name: id_sect
        description: "Identifiant de section"
      - name: src_sect
        description: "Source de la section"
      - name: autor_sect
        description: "Auteur de la section"
      - name: obs_vts
        description: "Observation sur les vitesses"
      - name: id_cpt1
        description: "Attributs de travail sur les compteurs (calcul sur Bdx Metropole notamment)"
