{% macro mcr_7_maj_nouv_point_lin(dept=var('dept'), annee=var('annee')) %}

-- Lignes présentes dans le seed (avec jointure)
select 
    -- Colonnes du seed, avec fallback sur cv si null
    anp.id_comptag,
    'otv' as src_cpt,
    'linearisation' as coment_cpt,
    case  
        when anp.coment_tmj_f is not null then anp.coment_tmj_f
        when anp.coment_tmj_f is null and cv.coment_tmj_f is not null then cv.coment_tmj_f
        when anp.coment_tmj_f is null and cv.coment_tmj_f is null and cv.sens in ('Sens direct','Sens inverse') then '/2' 
        when anp.coment_tmj_f is null and cv.coment_tmj_f is null and cv.sens='Double sens' then null 
        else null 
        end as coment_tmj_f,
    case when anp.obs_tmja is not null then anp.obs_tmja else cv.obs_tmja end as obs_tmja,
    case when anp.obs_pc_pl is not null then anp.obs_pc_pl else cv.obs_pc_pl end as obs_pc_pl,
    case when anp.obs_supl is not null then anp.obs_supl||';'||'nouveau point traf{{ annee }}' else 'nouveau point traf{{ annee }}' end as obs_supl,
    case when anp.id_sect is not null then anp.id_sect else cv.id_sect end as id_sect,
    case when anp.src_sect is not null then anp.src_sect else cv.src_sect end as src_sect,
    case when anp.autor_sect is not null then anp.autor_sect else cv.autor_sect end as autor_sect,
    case when anp.obs_vts is not null then anp.obs_vts else cv.obs_vts end as obs_vts,
    case when anp.id_cpt1 is not null then anp.id_cpt1 else cv.id_cpt1 end as id_cpt1,
    
    -- Colonnes de mdl1_creer_vue_19 non présentes dans le seed
    cv.id,
    cv.id_ign,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    cv.ann_pt,
    cv.src_cpteur,
    cv.coment_tmj,
    cv.ann_pc_pl,
    cv.tmja,
    cv.pc_pl,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.id_simpli,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ ref('sed7_dept' ~ dept ~ '_upd_nouv_pt') }} anp 
join {{ ref('mdl6_lin_upd_auto_pt_non_linear_' ~ dept)}} cv 
    on (array[cv.id_ign]::text[] && anp.id_ign) or (cv.id_simpli && anp.id_simpli)

UNION

-- Lignes de mdl6_lin_upd_auto_pt_non_linear_19 non présentes dans le seed
select 
    -- Colonnes correspondant au seed (avec valeurs de mdl6_lin_upd_auto_pt_non_linear_19)
    cv.id_comptag,
    cv.src_cpt,
    cv.coment_cpt,
    cv.coment_tmj_f,
    cv.obs_tmja,
    cv.obs_pc_pl,
    cv.obs_supl,
    cv.id_sect,
    cv.src_sect,
    cv.autor_sect,
    cv.obs_vts,
    cv.id_cpt1,
    
    -- Colonnes de mdl1_creer_vue_19
    cv.id,
    cv.id_ign,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    cv.ann_pt,
    cv.src_cpteur,
    cv.coment_tmj,
    cv.ann_pc_pl,
    cv.tmja,
    cv.pc_pl,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.id_simpli,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ ref('mdl6_lin_upd_auto_pt_non_linear_' ~ dept)}} cv
where not exists (
    select 1 
    from {{ ref('sed7_dept' ~ dept ~ '_upd_nouv_pt') }} anp
    where (array[cv.id_ign]::text[] && anp.id_ign) or (cv.id_simpli && anp.id_simpli)
)


{% endmacro %}

{# ─────────────────────────────────────────────────────────── #}

{% macro mcr_8_maj_modif_linear_lin(annee=var('annee'), dept=var('dept')) %}
{% set annee_prec = annee | int - 1 %}
-- Lignes présentes dans le seed (avec jointure)
select 
    -- Colonnes du seed : comme c'est une réaffectation c la seule colonne
    ml.id_comptag,
    -- Toutes les autres colonnes du modèle mdl1_creer_vue_19
    cv.id,
    cv.id_ign,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    cv.src_cpt,
    cv.coment_cpt,
    cv.ann_pt,
    cv.src_cpteur,
    cv.coment_tmj,
    cv.coment_tmj_f,
    cv.ann_pc_pl,
    cv.tmja,
    cv.pc_pl,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    cv.id_cpt1,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    cv.obs_tmja,
    cv.obs_pc_pl,
    case when cv.obs_supl is not null and cv.obs_supl like 'ex %' 
                    then 'ex '||cv.id_comptag||' traf{{ annee_prec }}'  ||','||cv.obs_supl 
                  when cv.obs_supl is not null 
                    then 'ex '||cv.id_comptag||' traf{{ annee_prec }}' ||',ex '||cv.obs_supl
                    else 'ex '||cv.id_comptag||' traf{{ annee_prec }}' 
                    end obs_supl,
    cv.id_sect,
    cv.src_sect,
    cv.autor_sect,
    cv.obs_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.id_simpli,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ ref('sed8_dept' ~ dept ~ '_upd_modif_linear') }} ml
join {{ ref('mdl7_lin_upd_nouv_point_' ~ dept) }} cv
    on (array[cv.id_ign]::text[] && ml.id_ign) or (cv.id_simpli && ml.id_simpli)

UNION

-- Lignes de mdl1_creer_vue_19 non présentes dans le seed
select 
    cv.id_comptag,
    -- Toutes les autres colonnes du modèle
    cv.id,
    cv.id_ign,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    cv.src_cpt,
    cv.coment_cpt,
    cv.ann_pt,
    cv.src_cpteur,
    cv.coment_tmj,
    cv.coment_tmj_f,
    cv.ann_pc_pl,
    cv.tmja,
    cv.pc_pl,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    cv.id_cpt1,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    cv.obs_tmja,
    cv.obs_pc_pl,
    cv.obs_supl,
    cv.id_sect,
    cv.src_sect,
    cv.autor_sect,
    cv.obs_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.id_simpli,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ ref('mdl7_lin_upd_nouv_point_' ~ dept) }} cv
where not exists (
    select 1 
    from {{ ref('sed8_dept' ~ dept ~ '_upd_modif_linear') }} ml
    where (array[cv.id_ign]::text[] && ml.id_ign) or (cv.id_simpli && ml.id_simpli)
)

{% endmacro %}

{# ─────────────────────────────────────────────────────────── #}

{% macro mcr_9_maj_oubli_erreur_lin(dept=var('dept')) %}

-- Lignes présentes dans le seed (avec jointure)
select 
    -- Colonnes du seed
    cv.id_comptag,
    cv.id_ign,
    cv.id_simpli,
    
    -- Toutes les autres colonnes du modèle
    cv.id,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    'otv' as src_cpt,
    'linearisation' as coment_cpt,
    cv.ann_pt,
    cv.src_cpteur,
    cv.coment_tmj,
    cv.coment_tmj_f,
    cv.ann_pc_pl,
    cv.tmja,
    cv.pc_pl,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    cv.id_cpt1,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    null as obs_tmja,
    null as obs_pc_pl,
    null as obs_supl,
    cv.id_sect,
    cv.src_sect,
    cv.autor_sect,
    cv.obs_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ ref('sed9_dept' ~ dept ~ '_upd_oubli_erreur_linear') }} uol
join {{ ref('mdl8_lin_upd_modif_linear_' ~ dept)}} cv
    on (array[cv.id_ign]::text[] && uol.id_ign) or (cv.id_simpli && uol.id_simpli)

UNION

-- Lignes de mdl1_creer_vue_19 non présentes dans le seed
select 
    cv.id_comptag,
    cv.id_ign,
    cv.id_simpli,
    
    -- Toutes les autres colonnes du modèle
    cv.id,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    cv.src_cpt,
    cv.coment_cpt,
    cv.ann_pt,
    cv.src_cpteur,
    cv.coment_tmj,
    cv.coment_tmj_f,
    cv.ann_pc_pl,
    cv.tmja,
    cv.pc_pl,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    cv.id_cpt1,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    cv.obs_tmja,
    cv.obs_pc_pl,
    cv.obs_supl,
    cv.id_sect,
    cv.src_sect,
    cv.autor_sect,
    cv.obs_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ ref('mdl8_lin_upd_modif_linear_' ~ dept)}} cv
where not exists (
    select 1 
    from {{ ref('sed9_dept' ~ dept ~ '_upd_oubli_erreur_linear') }} uol
    where (array[cv.id_ign]::text[] && uol.id_ign) or (cv.id_simpli && uol.id_simpli)
)

{% endmacro %}

{# ─────────────────────────────────────────────────────────── #}

{% macro mcr_10_maj_etirer_lin(dept=var('dept'), annee=var('annee')) %}

-- Lignes présentes dans le seed (avec jointure)
select 
    -- Colonnes du seed, avec fallback sur cv si null
    cv.id_comptag,
    cv.id_ign,
    cv.id_simpli,
    
    -- Toutes les autres colonnes du modèle
    cv.id,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    'otv' as src_cpt,
    'linearisation' as coment_cpt,
    cv.ann_pt,
    cv.src_cpteur,
    cv.coment_tmj,
    cv.coment_tmj_f,
    cv.ann_pc_pl,
    cv.tmja,
    cv.pc_pl,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    cv.id_cpt1,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    null as obs_tmja,
    null as obs_pc_pl,
    'linearisation etiree traf{{ annee }}' as obs_supl,
    cv.id_sect,
    cv.src_sect,
    cv.autor_sect,
    cv.obs_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ ref('sed10_dept' ~ dept ~ '_upd_etire_linear') }} uel
join {{ ref('mdl9_lin_upd_oubli_erreur_linear_' ~ dept)}} cv
    on (array[cv.id_ign]::text[] && uel.id_ign) or (cv.id_simpli && uel.id_simpli)

UNION

-- Lignes de mdl9_lin_upd_oubli_erreur_linear_19 non présentes dans le seed
select 
    cv.id_comptag,
    cv.id_ign,
    cv.id_simpli,
    
    -- Toutes les autres colonnes du modèle
    cv.id,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    cv.src_cpt,
    cv.coment_cpt,
    cv.ann_pt,
    cv.src_cpteur,
    cv.coment_tmj,
    cv.coment_tmj_f,
    cv.ann_pc_pl,
    cv.tmja,
    cv.pc_pl,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    cv.id_cpt1,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    cv.obs_tmja,
    cv.obs_pc_pl,
    cv.obs_supl,
    cv.id_sect,
    cv.src_sect,
    cv.autor_sect,
    cv.obs_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ ref('mdl9_lin_upd_oubli_erreur_linear_' ~ dept)}} cv
where not exists (
    select 1 
    from {{ ref('sed10_dept' ~ dept ~ '_upd_etire_linear') }} uel
    where (array[cv.id_ign]::text[] && uel.id_ign) or (cv.id_simpli && uel.id_simpli)
)

{% endmacro %}

{# ─────────────────────────────────────────────────────────── #}

{% macro mcr_11_maj_vers_estim_lin(dept=var('dept'), annee=var('annee')) %}
{% set annee_prec = annee | int - 1 %}

-- Lignes présentes dans le seed (avec jointure)
select 
    -- Colonnes spécifiques pour le passage vers estimation
    null as id_comptag,
    cv.id_ign,
    cv.id_simpli,
    
    -- Toutes les autres colonnes du modèle
    cv.id,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    null as src_cpt,
    'estimation' as coment_cpt,
    null as ann_pt,
    cv.src_cpteur,
    cv.coment_tmj,
    cv.coment_tmj_f,
    null as ann_pc_pl,
    cv.tmja,
    cv.pc_pl,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    null as id_cpt1,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    'auto' as obs_tmja,
    'auto' as obs_pc_pl,
    'maj a estimation traf{{ annee }},ex '||cv.id_comptag||' traf{{ annee_prec }}' as obs_supl,
    null as id_sect,
    null as src_sect,
    cv.autor_sect,
    null as obs_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ ref('sed11_dept' ~ dept ~ '_upd_vers_estim_linear') }} vel
join {{ ref('mdl10_lin_upd_etire_lin_' ~ dept)}} cv
    on (array[cv.id_ign]::text[] && vel.id_ign) or (cv.id_simpli && vel.id_simpli) or (cv.id_comptag = vel.id_comptag)

UNION

-- Lignes de mdl10_lin_upd_etire_lin_19 non présentes dans le seed
select 
    cv.id_comptag,
    cv.id_ign,
    cv.id_simpli,
    
    -- Toutes les autres colonnes du modèle
    cv.id,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    cv.src_cpt,
    cv.coment_cpt,
    cv.ann_pt,
    cv.src_cpteur,
    cv.coment_tmj,
    cv.coment_tmj_f,
    cv.ann_pc_pl,
    cv.tmja,
    cv.pc_pl,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    cv.id_cpt1,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    cv.obs_tmja,
    cv.obs_pc_pl,
    cv.obs_supl,
    cv.id_sect,
    cv.src_sect,
    cv.autor_sect,
    cv.obs_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ ref('mdl10_lin_upd_etire_lin_' ~ dept)}} cv
where not exists (
    select 1 
    from {{ ref('sed11_dept' ~ dept ~ '_upd_vers_estim_linear') }} vel
    where (array[cv.id_ign]::text[] && vel.id_ign) or (cv.id_simpli && vel.id_simpli) or (cv.id_comptag = vel.id_comptag)
)

{% endmacro %}

{# ─────────────────────────────────────────────────────────── #}

{% macro mcr_18a_maj_tmja_final_lin(dept=var('dept')) %}

select 
    ctf.id_comptag,
    ctf.id_ign,
    ctf.id_simpli,
    ctf.id,
    ctf.nature,
    ctf.nom_coll_g,
    ctf.nom_coll_d,
    ctf.numero,
    ctf.importance,
    ctf.cl_admin,
    ctf.gestion,
    ctf.fictif,
    ctf.largeur,
    ctf.nb_voies,
    ctf.sens,
    ctf.etat,
    ctf.inseecom_g,
    ctf.inseecom_d,
    ctf.id_voie_g,
    ctf.id_voie_d,
    ctf.urbain,
    ctf.vit_moy_vl,
    ctf.restr_p,
    ctf.dept,
    ctf.dept_2024,
    ctf.dept_2023,
    ctf.long_km,
    ctf.src_cpt,
    ctf.coment_cpt,
    ctf.ann_pt,
    ctf.src_cpteur,
    ctf.coment_tmj,
    ctf.coment_tmj_f,
    ctf.ann_pc_pl,
    ctf.tmja,
    ctf.pc_pl,
    ctf.veh_km,
    case when coment_tmj_f is null then round(tmja::numeric)::integer
        when coment_tmj_f='*2' then round(tmja::numeric*2.0)::integer
        when coment_tmj_f like '/%' and tmja<>0 then round(tmja::numeric/split_part(coment_tmj_f,'/',2)::numeric)::integer
        else null::integer end as tmja_final,
    ctf.pl,
    ctf.pl_final,
    ctf.pl_km,
    ctf.id_cpt1,
    ctf.id_cpt2,
    ctf.obs_tmj1,
    ctf.obs_tmj2,
    ctf.tmja_cpt1,
    ctf.tmja_cpt2,
    ctf.codau_cat,
    ctf.milieu,
    ctf.codau,
    ctf.type_vdf,
    ctf.vts_vl_vdf,
    ctf.vts_pl_vdf,
    ctf.vts_gest,
    ctf.id_vts,
    ctf.obs_tmja,
    ctf.obs_pc_pl,
    ctf.obs_supl,
    ctf.id_sect,
    ctf.src_sect,
    ctf.autor_sect,
    ctf.obs_vts,
    ctf.vts_osm,
    ctf.vts_modif,
    ctf.vts_vl_f,
    ctf.vts_pl_f,
    ctf.vts_type_vl,
    ctf.vts_type_pl,
    ctf.src_vma,
    ctf.vma_vl,
    ctf.vma_pl,
    ctf.vma_type,
    ctf.codau_cont,
    ctf.id_codau_cont,
    ctf.tmja_cont,
    ctf.pc_pl_cont,
    ctf."source",
    ctf.target,
    ctf.cnt_src,
    ctf.cnt_tgt,
    ctf.imp_sup,
    ctf.imp_sup_src,
    ctf.imp_sup_tgt,
    ctf.recup,
    ctf.id_cnt2,
    ctf.id_struct_rout,
    ctf.id_sect_hom,
    ctf.attr_modif,
    ctf.id_bdc,
    ctf.geom,
    ctf.ang_orient_src_vert1,
    ctf.ang_orient_tgt_vert1,
    ctf.list_id_inter,
    ctf.nb_nod_non_topo,
    ctf.id_struct
from {{ref('mdl17a_lin_upd_cmt_tmj_f_sens_dbl_spl_' ~ dept)}} ctf
where ctf.coment_cpt = 'linearisation'
union
select 
    ctf.id_comptag,
    ctf.id_ign,
    ctf.id_simpli,
    ctf.id,
    ctf.nature,
    ctf.nom_coll_g,
    ctf.nom_coll_d,
    ctf.numero,
    ctf.importance,
    ctf.cl_admin,
    ctf.gestion,
    ctf.fictif,
    ctf.largeur,
    ctf.nb_voies,
    ctf.sens,
    ctf.etat,
    ctf.inseecom_g,
    ctf.inseecom_d,
    ctf.id_voie_g,
    ctf.id_voie_d,
    ctf.urbain,
    ctf.vit_moy_vl,
    ctf.restr_p,
    ctf.dept,
    ctf.dept_2024,
    ctf.dept_2023,
    ctf.long_km,
    ctf.src_cpt,
    ctf.coment_cpt,
    ctf.ann_pt,
    ctf.src_cpteur,
    ctf.coment_tmj,
    ctf.coment_tmj_f,
    ctf.ann_pc_pl,
    ctf.tmja,
    ctf.pc_pl,
    ctf.veh_km,
    ctf.tmja_final,
    ctf.pl,
    ctf.pl_final,
    ctf.pl_km,
    ctf.id_cpt1,
    ctf.id_cpt2,
    ctf.obs_tmj1,
    ctf.obs_tmj2,
    ctf.tmja_cpt1,
    ctf.tmja_cpt2,
    ctf.codau_cat,
    ctf.milieu,
    ctf.codau,
    ctf.type_vdf,
    ctf.vts_vl_vdf,
    ctf.vts_pl_vdf,
    ctf.vts_gest,
    ctf.id_vts,
    ctf.obs_tmja,
    ctf.obs_pc_pl,
    ctf.obs_supl,
    ctf.id_sect,
    ctf.src_sect,
    ctf.autor_sect,
    ctf.obs_vts,
    ctf.vts_osm,
    ctf.vts_modif,
    ctf.vts_vl_f,
    ctf.vts_pl_f,
    ctf.vts_type_vl,
    ctf.vts_type_pl,
    ctf.src_vma,
    ctf.vma_vl,
    ctf.vma_pl,
    ctf.vma_type,
    ctf.codau_cont,
    ctf.id_codau_cont,
    ctf.tmja_cont,
    ctf.pc_pl_cont,
    ctf."source",
    ctf.target,
    ctf.cnt_src,
    ctf.cnt_tgt,
    ctf.imp_sup,
    ctf.imp_sup_src,
    ctf.imp_sup_tgt,
    ctf.recup,
    ctf.id_cnt2,
    ctf.id_struct_rout,
    ctf.id_sect_hom,
    ctf.attr_modif,
    ctf.id_bdc,
    ctf.geom,
    ctf.ang_orient_src_vert1,
    ctf.ang_orient_tgt_vert1,
    ctf.list_id_inter,
    ctf.nb_nod_non_topo,
    ctf.id_struct
from {{ref('mdl17a_lin_upd_cmt_tmj_f_sens_dbl_spl_' ~ dept)}} ctf
where ctf.coment_cpt != 'linearisation' or ctf.coment_cpt is null

{% endmacro %}

{# ─────────────────────────────────────────────────────────── #}

{% macro mcr_19_maj_veh_km_lin(dept=var('dept')) %}

select 
    ctf.id_comptag,
    ctf.id_ign,
    ctf.id_simpli,
    ctf.id,
    ctf.nature,
    ctf.nom_coll_g,
    ctf.nom_coll_d,
    ctf.numero,
    ctf.importance,
    ctf.cl_admin,
    ctf.gestion,
    ctf.fictif,
    ctf.largeur,
    ctf.nb_voies,
    ctf.sens,
    ctf.etat,
    ctf.inseecom_g,
    ctf.inseecom_d,
    ctf.id_voie_g,
    ctf.id_voie_d,
    ctf.urbain,
    ctf.vit_moy_vl,
    ctf.restr_p,
    ctf.dept,
    ctf.dept_2024,
    ctf.dept_2023,
    ctf.long_km,
    ctf.src_cpt,
    ctf.coment_cpt,
    ctf.ann_pt,
    ctf.src_cpteur,
    ctf.coment_tmj,
    ctf.coment_tmj_f,
    ctf.ann_pc_pl,
    ctf.tmja,
    ctf.pc_pl,
    tmja_final*long_km as veh_km,
    ctf.tmja_final,
    ctf.pl,
    ctf.pl_final,
    ctf.pl_km,
    ctf.id_cpt1,
    ctf.id_cpt2,
    ctf.obs_tmj1,
    ctf.obs_tmj2,
    ctf.tmja_cpt1,
    ctf.tmja_cpt2,
    ctf.codau_cat,
    ctf.milieu,
    ctf.codau,
    ctf.type_vdf,
    ctf.vts_vl_vdf,
    ctf.vts_pl_vdf,
    ctf.vts_gest,
    ctf.id_vts,
    ctf.obs_tmja,
    ctf.obs_pc_pl,
    ctf.obs_supl,
    ctf.id_sect,
    ctf.src_sect,
    ctf.autor_sect,
    ctf.obs_vts,
    ctf.vts_osm,
    ctf.vts_modif,
    ctf.vts_vl_f,
    ctf.vts_pl_f,
    ctf.vts_type_vl,
    ctf.vts_type_pl,
    ctf.src_vma,
    ctf.vma_vl,
    ctf.vma_pl,
    ctf.vma_type,
    ctf.codau_cont,
    ctf.id_codau_cont,
    ctf.tmja_cont,
    ctf.pc_pl_cont,
    ctf."source",
    ctf.target,
    ctf.cnt_src,
    ctf.cnt_tgt,
    ctf.imp_sup,
    ctf.imp_sup_src,
    ctf.imp_sup_tgt,
    ctf.recup,
    ctf.id_cnt2,
    ctf.id_struct_rout,
    ctf.id_sect_hom,
    ctf.attr_modif,
    ctf.id_bdc,
    ctf.geom,
    ctf.ang_orient_src_vert1,
    ctf.ang_orient_tgt_vert1,
    ctf.list_id_inter,
    ctf.nb_nod_non_topo,
    ctf.id_struct
from {{ref('mdl18a_lin_upd_tmja_final_' ~ dept)}} ctf
where ctf.coment_cpt = 'linearisation'
union
select 
    ctf.id_comptag,
    ctf.id_ign,
    ctf.id_simpli,
    ctf.id,
    ctf.nature,
    ctf.nom_coll_g,
    ctf.nom_coll_d,
    ctf.numero,
    ctf.importance,
    ctf.cl_admin,
    ctf.gestion,
    ctf.fictif,
    ctf.largeur,
    ctf.nb_voies,
    ctf.sens,
    ctf.etat,
    ctf.inseecom_g,
    ctf.inseecom_d,
    ctf.id_voie_g,
    ctf.id_voie_d,
    ctf.urbain,
    ctf.vit_moy_vl,
    ctf.restr_p,
    ctf.dept,
    ctf.dept_2024,
    ctf.dept_2023,
    ctf.long_km,
    ctf.src_cpt,
    ctf.coment_cpt,
    ctf.ann_pt,
    ctf.src_cpteur,
    ctf.coment_tmj,
    ctf.coment_tmj_f,
    ctf.ann_pc_pl,
    ctf.tmja,
    ctf.pc_pl,
    ctf.veh_km,
    ctf.tmja_final,
    ctf.pl,
    ctf.pl_final,
    ctf.pl_km,
    ctf.id_cpt1,
    ctf.id_cpt2,
    ctf.obs_tmj1,
    ctf.obs_tmj2,
    ctf.tmja_cpt1,
    ctf.tmja_cpt2,
    ctf.codau_cat,
    ctf.milieu,
    ctf.codau,
    ctf.type_vdf,
    ctf.vts_vl_vdf,
    ctf.vts_pl_vdf,
    ctf.vts_gest,
    ctf.id_vts,
    ctf.obs_tmja,
    ctf.obs_pc_pl,
    ctf.obs_supl,
    ctf.id_sect,
    ctf.src_sect,
    ctf.autor_sect,
    ctf.obs_vts,
    ctf.vts_osm,
    ctf.vts_modif,
    ctf.vts_vl_f,
    ctf.vts_pl_f,
    ctf.vts_type_vl,
    ctf.vts_type_pl,
    ctf.src_vma,
    ctf.vma_vl,
    ctf.vma_pl,
    ctf.vma_type,
    ctf.codau_cont,
    ctf.id_codau_cont,
    ctf.tmja_cont,
    ctf.pc_pl_cont,
    ctf."source",
    ctf.target,
    ctf.cnt_src,
    ctf.cnt_tgt,
    ctf.imp_sup,
    ctf.imp_sup_src,
    ctf.imp_sup_tgt,
    ctf.recup,
    ctf.id_cnt2,
    ctf.id_struct_rout,
    ctf.id_sect_hom,
    ctf.attr_modif,
    ctf.id_bdc,
    ctf.geom,
    ctf.ang_orient_src_vert1,
    ctf.ang_orient_tgt_vert1,
    ctf.list_id_inter,
    ctf.nb_nod_non_topo,
    ctf.id_struct
from {{ref('mdl18a_lin_upd_tmja_final_' ~ dept)}} ctf
where ctf.coment_cpt != 'linearisation' or ctf.coment_cpt is null

{% endmacro %}

{# ─────────────────────────────────────────────────────────── #}

{% macro mcr_20_maj_pl_final_pl_km_lin(dept=var('dept')) %}

select 
    ctf.id_comptag,
    ctf.id_ign,
    ctf.id_simpli,
    ctf.id,
    ctf.nature,
    ctf.nom_coll_g,
    ctf.nom_coll_d,
    ctf.numero,
    ctf.importance,
    ctf.cl_admin,
    ctf.gestion,
    ctf.fictif,
    ctf.largeur,
    ctf.nb_voies,
    ctf.sens,
    ctf.etat,
    ctf.inseecom_g,
    ctf.inseecom_d,
    ctf.id_voie_g,
    ctf.id_voie_d,
    ctf.urbain,
    ctf.vit_moy_vl,
    ctf.restr_p,
    ctf.dept,
    ctf.dept_2024,
    ctf.dept_2023,
    ctf.long_km,
    ctf.src_cpt,
    ctf.coment_cpt,
    ctf.ann_pt,
    ctf.src_cpteur,
    ctf.coment_tmj,
    ctf.coment_tmj_f,
    ctf.ann_pc_pl,
    ctf.tmja,
    ctf.pc_pl,
    ctf.veh_km,
    ctf.tmja_final,
    ctf.pl,
    case when ctf.coment_tmj_f is null and ctf.pl=0 then 0::integer
        when ctf.coment_tmj_f is null and ctf.pl<>0 then round(ctf.pl::numeric)::integer
        when ctf.coment_tmj_f='*2' and ctf.pl=0 then 0::integer
        when ctf.coment_tmj_f='*2' and ctf.pl<>0 then round(ctf.pl::numeric*2.0)::integer
        when ctf.coment_tmj_f like '/%' and ctf.pl=0 then 0::integer
        when ctf.coment_tmj_f like '/%' and ctf.pl<>0 then round(ctf.pl::numeric/split_part(ctf.coment_tmj_f,'/',2)::numeric)::integer
        else null::integer end as pl_final,
    case when ctf.coment_tmj_f is null and ctf.pl=0 then 0::numeric
        when ctf.coment_tmj_f is null and ctf.pl<>0 then round(ctf.pl::numeric)::integer*long_km::numeric
        when ctf.coment_tmj_f='*2' and ctf.pl=0 then 0::numeric
        when ctf.coment_tmj_f='*2' and ctf.pl<>0 then round(ctf.pl::numeric*2.0)::integer*long_km::numeric*2.0::numeric
        when ctf.coment_tmj_f like '/%' and ctf.pl=0 then 0::numeric
        when ctf.coment_tmj_f like '/%' and ctf.pl<>0 then round(ctf.pl::numeric/split_part(ctf.coment_tmj_f,'/',2)::numeric)::integer*long_km::numeric
        else null::numeric end as pl_km,
    ctf.id_cpt1,
    ctf.id_cpt2,
    ctf.obs_tmj1,
    ctf.obs_tmj2,
    ctf.tmja_cpt1,
    ctf.tmja_cpt2,
    ctf.codau_cat,
    ctf.milieu,
    ctf.codau,
    ctf.type_vdf,
    ctf.vts_vl_vdf,
    ctf.vts_pl_vdf,
    ctf.vts_gest,
    ctf.id_vts,
    ctf.obs_tmja,
    ctf.obs_pc_pl,
    ctf.obs_supl,
    ctf.id_sect,
    ctf.src_sect,
    ctf.autor_sect,
    ctf.obs_vts,
    ctf.vts_osm,
    ctf.vts_modif,
    ctf.vts_vl_f,
    ctf.vts_pl_f,
    ctf.vts_type_vl,
    ctf.vts_type_pl,
    ctf.src_vma,
    ctf.vma_vl,
    ctf.vma_pl,
    ctf.vma_type,
    ctf.codau_cont,
    ctf.id_codau_cont,
    ctf.tmja_cont,
    ctf.pc_pl_cont,
    ctf."source",
    ctf.target,
    ctf.cnt_src,
    ctf.cnt_tgt,
    ctf.imp_sup,
    ctf.imp_sup_src,
    ctf.imp_sup_tgt,
    ctf.recup,
    ctf.id_cnt2,
    ctf.id_struct_rout,
    ctf.id_sect_hom,
    ctf.attr_modif,
    ctf.id_bdc,
    ctf.geom,
    ctf.ang_orient_src_vert1,
    ctf.ang_orient_tgt_vert1,
    ctf.list_id_inter,
    ctf.nb_nod_non_topo,
    ctf.id_struct
from {{ref('mdl19_lin_upd_veh_km_' ~ dept)}} ctf
where ctf.coment_cpt = 'linearisation' and pl is not null
union
select 
    ctf.id_comptag,
    ctf.id_ign,
    ctf.id_simpli,
    ctf.id,
    ctf.nature,
    ctf.nom_coll_g,
    ctf.nom_coll_d,
    ctf.numero,
    ctf.importance,
    ctf.cl_admin,
    ctf.gestion,
    ctf.fictif,
    ctf.largeur,
    ctf.nb_voies,
    ctf.sens,
    ctf.etat,
    ctf.inseecom_g,
    ctf.inseecom_d,
    ctf.id_voie_g,
    ctf.id_voie_d,
    ctf.urbain,
    ctf.vit_moy_vl,
    ctf.restr_p,
    ctf.dept,
    ctf.dept_2024,
    ctf.dept_2023,
    ctf.long_km,
    ctf.src_cpt,
    ctf.coment_cpt,
    ctf.ann_pt,
    ctf.src_cpteur,
    ctf.coment_tmj,
    ctf.coment_tmj_f,
    ctf.ann_pc_pl,
    ctf.tmja,
    ctf.pc_pl,
    ctf.veh_km,
    ctf.tmja_final,
    ctf.pl,
    ctf.pl_final,
    ctf.pl_km,
    ctf.id_cpt1,
    ctf.id_cpt2,
    ctf.obs_tmj1,
    ctf.obs_tmj2,
    ctf.tmja_cpt1,
    ctf.tmja_cpt2,
    ctf.codau_cat,
    ctf.milieu,
    ctf.codau,
    ctf.type_vdf,
    ctf.vts_vl_vdf,
    ctf.vts_pl_vdf,
    ctf.vts_gest,
    ctf.id_vts,
    ctf.obs_tmja,
    ctf.obs_pc_pl,
    ctf.obs_supl,
    ctf.id_sect,
    ctf.src_sect,
    ctf.autor_sect,
    ctf.obs_vts,
    ctf.vts_osm,
    ctf.vts_modif,
    ctf.vts_vl_f,
    ctf.vts_pl_f,
    ctf.vts_type_vl,
    ctf.vts_type_pl,
    ctf.src_vma,
    ctf.vma_vl,
    ctf.vma_pl,
    ctf.vma_type,
    ctf.codau_cont,
    ctf.id_codau_cont,
    ctf.tmja_cont,
    ctf.pc_pl_cont,
    ctf."source",
    ctf.target,
    ctf.cnt_src,
    ctf.cnt_tgt,
    ctf.imp_sup,
    ctf.imp_sup_src,
    ctf.imp_sup_tgt,
    ctf.recup,
    ctf.id_cnt2,
    ctf.id_struct_rout,
    ctf.id_sect_hom,
    ctf.attr_modif,
    ctf.id_bdc,
    ctf.geom,
    ctf.ang_orient_src_vert1,
    ctf.ang_orient_tgt_vert1,
    ctf.list_id_inter,
    ctf.nb_nod_non_topo,
    ctf.id_struct
from {{ref('mdl19_lin_upd_veh_km_' ~ dept)}} ctf
where ctf.coment_cpt != 'linearisation' or ctf.coment_cpt is null or ctf.pl is null

{% endmacro %}

{# ─────────────────────────────────────────────────────────── #}

{% macro mcr_21a_maj_cmt_cpt_lin(dept=var('dept')) %}

select 
    ctf.id_comptag,
    ctf.id_ign,
    ctf.id_simpli,
    ctf.id,
    ctf.nature,
    ctf.nom_coll_g,
    ctf.nom_coll_d,
    ctf.numero,
    ctf.importance,
    ctf.cl_admin,
    ctf.gestion,
    ctf.fictif,
    ctf.largeur,
    ctf.nb_voies,
    ctf.sens,
    ctf.etat,
    ctf.inseecom_g,
    ctf.inseecom_d,
    ctf.id_voie_g,
    ctf.id_voie_d,
    ctf.urbain,
    ctf.vit_moy_vl,
    ctf.restr_p,
    ctf.dept,
    ctf.dept_2024,
    ctf.dept_2023,
    ctf.long_km,
    ctf.src_cpt,
    case when ctf.src_cpt = 'otv' then 'linearisation' else 'estimation' end as coment_cpt,
    ctf.ann_pt,
    ctf.src_cpteur,
    ctf.coment_tmj,
    ctf.coment_tmj_f,
    ctf.ann_pc_pl,
    ctf.tmja,
    ctf.pc_pl,
    ctf.veh_km,
    ctf.tmja_final,
    ctf.pl,
    ctf.pl_final,
    ctf.pl_km,
    ctf.id_cpt1,
    ctf.id_cpt2,
    ctf.obs_tmj1,
    ctf.obs_tmj2,
    ctf.tmja_cpt1,
    ctf.tmja_cpt2,
    ctf.codau_cat,
    ctf.milieu,
    ctf.codau,
    ctf.type_vdf,
    ctf.vts_vl_vdf,
    ctf.vts_pl_vdf,
    ctf.vts_gest,
    ctf.id_vts,
    ctf.obs_tmja,
    ctf.obs_pc_pl,
    ctf.obs_supl,
    ctf.id_sect,
    ctf.src_sect,
    ctf.autor_sect,
    ctf.obs_vts,
    ctf.vts_osm,
    ctf.vts_modif,
    ctf.vts_vl_f,
    ctf.vts_pl_f,
    ctf.vts_type_vl,
    ctf.vts_type_pl,
    ctf.src_vma,
    ctf.vma_vl,
    ctf.vma_pl,
    ctf.vma_type,
    ctf.codau_cont,
    ctf.id_codau_cont,
    ctf.tmja_cont,
    ctf.pc_pl_cont,
    ctf."source",
    ctf.target,
    ctf.cnt_src,
    ctf.cnt_tgt,
    ctf.imp_sup,
    ctf.imp_sup_src,
    ctf.imp_sup_tgt,
    ctf.recup,
    ctf.id_cnt2,
    ctf.id_struct_rout,
    ctf.id_sect_hom,
    ctf.attr_modif,
    ctf.id_bdc,
    ctf.geom,
    ctf.ang_orient_src_vert1,
    ctf.ang_orient_tgt_vert1,
    ctf.list_id_inter,
    ctf.nb_nod_non_topo,
    ctf.id_struct
from {{ref('mdl20_lin_upd_pl_final_pl_km_' ~ dept)}} ctf

{% endmacro %}

{# ─────────────────────────────────────────────────────────── #}

{% macro mcr_22_maj_cmt_tmj_f_estim_lin(dept=var('dept')) %}

select 
    ctf.id_comptag,
    ctf.id_ign,
    ctf.id_simpli,
    ctf.id,
    ctf.nature,
    ctf.nom_coll_g,
    ctf.nom_coll_d,
    ctf.numero,
    ctf.importance,
    ctf.cl_admin,
    ctf.gestion,
    ctf.fictif,
    ctf.largeur,
    ctf.nb_voies,
    ctf.sens,
    ctf.etat,
    ctf.inseecom_g,
    ctf.inseecom_d,
    ctf.id_voie_g,
    ctf.id_voie_d,
    ctf.urbain,
    ctf.vit_moy_vl,
    ctf.restr_p,
    ctf.dept,
    ctf.dept_2024,
    ctf.dept_2023,
    ctf.long_km,
    ctf.src_cpt,
    ctf.coment_cpt,
    ctf.ann_pt,
    ctf.src_cpteur,
    ctf.coment_tmj,
    case when sens='{{var("bdtopo_double_sens_verif")}}' then null 
         when sens=ANY(ARRAY{{var('bdtopo_sens_uniq_verif')}}) then '/2' else null end as coment_tmj_f,
    ctf.ann_pc_pl,
    ctf.tmja,
    ctf.pc_pl,
    ctf.veh_km,
    ctf.tmja_final,
    ctf.pl,
    ctf.pl_final,
    ctf.pl_km,
    ctf.id_cpt1,
    ctf.id_cpt2,
    ctf.obs_tmj1,
    ctf.obs_tmj2,
    ctf.tmja_cpt1,
    ctf.tmja_cpt2,
    ctf.codau_cat,
    ctf.milieu,
    ctf.codau,
    ctf.type_vdf,
    ctf.vts_vl_vdf,
    ctf.vts_pl_vdf,
    ctf.vts_gest,
    ctf.id_vts,
    ctf.obs_tmja,
    ctf.obs_pc_pl,
    ctf.obs_supl,
    ctf.id_sect,
    ctf.src_sect,
    ctf.autor_sect,
    ctf.obs_vts,
    ctf.vts_osm,
    ctf.vts_modif,
    ctf.vts_vl_f,
    ctf.vts_pl_f,
    ctf.vts_type_vl,
    ctf.vts_type_pl,
    ctf.src_vma,
    ctf.vma_vl,
    ctf.vma_pl,
    ctf.vma_type,
    ctf.codau_cont,
    ctf.id_codau_cont,
    ctf.tmja_cont,
    ctf.pc_pl_cont,
    ctf."source",
    ctf.target,
    ctf.cnt_src,
    ctf.cnt_tgt,
    ctf.imp_sup,
    ctf.imp_sup_src,
    ctf.imp_sup_tgt,
    ctf.recup,
    ctf.id_cnt2,
    ctf.id_struct_rout,
    ctf.id_sect_hom,
    ctf.attr_modif,
    ctf.id_bdc,
    ctf.geom,
    ctf.ang_orient_src_vert1,
    ctf.ang_orient_tgt_vert1,
    ctf.list_id_inter,
    ctf.nb_nod_non_topo,
    ctf.id_struct
from {{ref('mdl21a_lin_upd_cmt_cpt_' ~ dept)}} ctf
where ctf.coment_cpt = 'estimation' and src_cpt is null
UNION
select 
    ctf.id_comptag,
    ctf.id_ign,
    ctf.id_simpli,
    ctf.id,
    ctf.nature,
    ctf.nom_coll_g,
    ctf.nom_coll_d,
    ctf.numero,
    ctf.importance,
    ctf.cl_admin,
    ctf.gestion,
    ctf.fictif,
    ctf.largeur,
    ctf.nb_voies,
    ctf.sens,
    ctf.etat,
    ctf.inseecom_g,
    ctf.inseecom_d,
    ctf.id_voie_g,
    ctf.id_voie_d,
    ctf.urbain,
    ctf.vit_moy_vl,
    ctf.restr_p,
    ctf.dept,
    ctf.dept_2024,
    ctf.dept_2023,
    ctf.long_km,
    ctf.src_cpt,
    ctf.coment_cpt,
    ctf.ann_pt,
    ctf.src_cpteur,
    ctf.coment_tmj,
    ctf.coment_tmj_f,
    ctf.ann_pc_pl,
    ctf.tmja,
    ctf.pc_pl,
    ctf.veh_km,
    ctf.tmja_final,
    ctf.pl,
    ctf.pl_final,
    ctf.pl_km,
    ctf.id_cpt1,
    ctf.id_cpt2,
    ctf.obs_tmj1,
    ctf.obs_tmj2,
    ctf.tmja_cpt1,
    ctf.tmja_cpt2,
    ctf.codau_cat,
    ctf.milieu,
    ctf.codau,
    ctf.type_vdf,
    ctf.vts_vl_vdf,
    ctf.vts_pl_vdf,
    ctf.vts_gest,
    ctf.id_vts,
    ctf.obs_tmja,
    ctf.obs_pc_pl,
    ctf.obs_supl,
    ctf.id_sect,
    ctf.src_sect,
    ctf.autor_sect,
    ctf.obs_vts,
    ctf.vts_osm,
    ctf.vts_modif,
    ctf.vts_vl_f,
    ctf.vts_pl_f,
    ctf.vts_type_vl,
    ctf.vts_type_pl,
    ctf.src_vma,
    ctf.vma_vl,
    ctf.vma_pl,
    ctf.vma_type,
    ctf.codau_cont,
    ctf.id_codau_cont,
    ctf.tmja_cont,
    ctf.pc_pl_cont,
    ctf."source",
    ctf.target,
    ctf.cnt_src,
    ctf.cnt_tgt,
    ctf.imp_sup,
    ctf.imp_sup_src,
    ctf.imp_sup_tgt,
    ctf.recup,
    ctf.id_cnt2,
    ctf.id_struct_rout,
    ctf.id_sect_hom,
    ctf.attr_modif,
    ctf.id_bdc,
    ctf.geom,
    ctf.ang_orient_src_vert1,
    ctf.ang_orient_tgt_vert1,
    ctf.list_id_inter,
    ctf.nb_nod_non_topo,
    ctf.id_struct
from {{ref('mdl21a_lin_upd_cmt_cpt_' ~ dept)}} ctf
where ctf.coment_cpt != 'estimation' and src_cpt is not null

{% endmacro %}
