{% macro affecter_point_lin(dept=var('dept')) %}

-- Lignes présentes dans le seed (avec jointure)
select 
    -- Colonnes du seed
    anp.id_comptag,
    anp.id_ign,
    anp.src_cpt,
    anp.coment_cpt,
    case  
        when anp.coment_tmj_f is not null then anp.coment_tmj_f
        when anp.coment_tmj_f is null and cv.coment_tmj_f is not null then cv.coment_tmj_f
        when anp.coment_tmj_f is null and cv.coment_tmj_f is null and cv.sens in ('Sens direct','Sens inverse') then '/2' 
        when anp.coment_tmj_f is null and cv.coment_tmj_f is null and cv.sens='Double sens' then null 
        else null 
        end as coment_tmj_f,
    anp.obs_tmja,
    anp.obs_pc_pl,
    anp.ann_pt::char(4),
    anp.ann_pc_pl::char(4),
    anp.tmja,
    anp.pc_pl,
    anp.obs_supl,
    anp.id_sect,
    anp.src_sect,
    anp.autor_sect,
    anp.obs_vts,
    anp.id_cpt1,
    
    -- Colonnes de creer_vue_19 non présentes dans le seed
    cv.id,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.id_simpli,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ ref('dept' ~ dept ~ '_affectation_pt_mano') }} anp 
join {{ ref('creer_vue_' ~ dept)}} cv on anp.id_ign = cv.id_ign

UNION

-- Lignes de creer_vue_19 non présentes dans le seed
select 
    -- Colonnes correspondant au seed (avec valeurs de creer_vue_19)
    cv.id_comptag,
    cv.id_ign,
    cv.src_cpt,
    cv.coment_cpt,
    cv.coment_tmj_f,
    cv.obs_tmja,
    cv.obs_pc_pl,
    cv.ann_pt,
    cv.ann_pc_pl,
    cv.tmja,
    cv.pc_pl,
    cv.obs_supl,
    cv.id_sect,
    cv.src_sect,
    cv.autor_sect,
    cv.obs_vts,
    cv.id_cpt1,
    
    -- Colonnes de creer_vue_19
    cv.id,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.id_simpli,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ ref('creer_vue_' ~ dept)}} cv
where not exists (
    select 1 
    from {{ ref('dept' ~ dept ~ '_affectation_pt_mano') }} anp
    where anp.id_ign = cv.id_ign
)


{% endmacro %}