{% macro cte_verif_cpt_mm_section_homo_lin__lineaire_tot(dept=var('dept'), distance=100) %}

SELECT 
    lin.id, 
    lin.id_ign, 
    lin.nature, 
    lin.nom_coll_g, 
    lin.nom_coll_d, 
    lin.numero, 
    lin.importance, 
    lin.cl_admin, 
    lin.gestion, 
    lin.fictif, 
    lin.largeur, 
    lin.nb_voies, 
    lin.sens, 
    lin.etat, 
    lin.inseecom_g, 
    lin.inseecom_d, 
    lin.id_voie_g, 
    lin.id_voie_d, 
    lin.urbain, 
    lin.vit_moy_vl, 
    lin.restr_p, 
    lin.dept, 
    lin.dept_2024, 
    lin.dept_2023, 
    lin.long_km, 
    lin.coment_cpt, 
    lin.id_comptag, 
    lin.src_cpt, 
    lin.obs_supl,
    lin.ann_pt, 
    lin.coment_tmj, 
    lin.coment_tmj_f, 
    lin.tmja, 
    lin.tmja_final, 
    lin.veh_km, 
    lin.ann_pc_pl, 
    lin.pc_pl, 
    lin.pl, 
    lin.pl_final, 
    lin.pl_km, 
    lin.obs_tmja, 
    lin.obs_pc_pl, 
    lin.id_cpt1, 
    lin.id_cpt2, 
    lin.obs_tmj1, 
    lin.obs_tmj2, 
    lin.tmja_cpt1, 
    lin.tmja_cpt2, 
    lin.id_sect, 
    lin.src_sect, 
    lin.autor_sect, 
    lin.codau_cat, 
    lin.milieu, 
    lin.codau, 
    lin.type_vdf, 
    lin.vts_vl_vdf, 
    lin.vts_pl_vdf, 
    lin.vts_gest, 
    lin.id_vts, 
    lin.obs_vts, 
    lin.vts_osm, 
    lin.vts_modif, 
    lin.vts_vl_f, 
    lin.vts_pl_f, 
    lin.vts_type_vl, 
    lin.vts_type_pl, 
    lin.src_vma, 
    lin.vma_vl, 
    lin.vma_pl, 
    lin.vma_type, 
    lin.codau_cont, 
    lin.id_codau_cont, 
    lin.tmja_cont, 
    lin.pc_pl_cont, 
    lin."source", 
    lin.target, 
    lin.cnt_src, 
    lin.cnt_tgt, 
    lin.imp_sup, 
    lin.imp_sup_src, 
    lin.imp_sup_tgt, 
    lin.recup, 
    lin.id_cnt2, 
    lin.id_struct_rout, 
    lin.id_sect_hom, 
    lin.id_simpli, 
    lin.attr_modif, 
    lin.id_bdc, 
    lin.geom, 
    lin.ang_orient_src_vert1, 
    lin.ang_orient_tgt_vert1, 
    lin.list_id_inter, 
    lin.nb_nod_non_topo, 
    lin.id_struct,
    -- Colonne id_cpt_proche
    CASE WHEN cpt_proche.id_comptag IS NOT NULL THEN TRUE ELSE FALSE END AS id_cpt_proch
FROM {{ ref('lin_update_vers_estimation_' ~ dept) }} lin
LEFT JOIN ({{ cte_verif_cpt_mm_section_homo__cpt_proche(dept=dept, distance=distance) }}) as cpt_proche 
    ON lin.id_ign = cpt_proche.id_ign 
    AND lin.id_comptag = cpt_proche.id_comptag

{% endmacro %}