{% macro mcr_20_maj_pl_final_pl_km_lin(dept=var('dept')) %}

select 
    ctf.id_comptag,
    ctf.id_ign,
    ctf.id_simpli,
    ctf.id,
    ctf.nature,
    ctf.nom_coll_g,
    ctf.nom_coll_d,
    ctf.numero,
    ctf.importance,
    ctf.cl_admin,
    ctf.gestion,
    ctf.fictif,
    ctf.largeur,
    ctf.nb_voies,
    ctf.sens,
    ctf.etat,
    ctf.inseecom_g,
    ctf.inseecom_d,
    ctf.id_voie_g,
    ctf.id_voie_d,
    ctf.urbain,
    ctf.vit_moy_vl,
    ctf.restr_p,
    ctf.dept,
    ctf.dept_2024,
    ctf.dept_2023,
    ctf.long_km,
    ctf.src_cpt,
    ctf.coment_cpt,
    ctf.ann_pt,
    ctf.src_cpteur,
    ctf.coment_tmj,
    ctf.coment_tmj_f,
    ctf.ann_pc_pl,
    ctf.tmja,
    ctf.pc_pl,
    ctf.veh_km,
    ctf.tmja_final,
    ctf.pl,
    case when ctf.coment_tmj_f is null and ctf.pl=0 then 0::integer
        when ctf.coment_tmj_f is null and ctf.pl<>0 then round(ctf.pl::numeric)::integer
        when ctf.coment_tmj_f='*2' and ctf.pl=0 then 0::integer
        when ctf.coment_tmj_f='*2' and ctf.pl<>0 then round(ctf.pl::numeric*2.0)::integer
        when ctf.coment_tmj_f like '/%' and ctf.pl=0 then 0::integer
        when ctf.coment_tmj_f like '/%' and ctf.pl<>0 then round(ctf.pl::numeric/split_part(ctf.coment_tmj_f,'/',2)::numeric)::integer
        else null::integer end as pl_final,
    case when ctf.coment_tmj_f is null and ctf.pl=0 then 0::numeric
        when ctf.coment_tmj_f is null and ctf.pl<>0 then round(ctf.pl::numeric)::integer*long_km::numeric
        when ctf.coment_tmj_f='*2' and ctf.pl=0 then 0::numeric
        when ctf.coment_tmj_f='*2' and ctf.pl<>0 then round(ctf.pl::numeric*2.0)::integer*long_km::numeric*2.0::numeric
        when ctf.coment_tmj_f like '/%' and ctf.pl=0 then 0::numeric
        when ctf.coment_tmj_f like '/%' and ctf.pl<>0 then round(ctf.pl::numeric/split_part(ctf.coment_tmj_f,'/',2)::numeric)::integer*long_km::numeric
        else null::numeric end as pl_km,
    ctf.id_cpt1,
    ctf.id_cpt2,
    ctf.obs_tmj1,
    ctf.obs_tmj2,
    ctf.tmja_cpt1,
    ctf.tmja_cpt2,
    ctf.codau_cat,
    ctf.milieu,
    ctf.codau,
    ctf.type_vdf,
    ctf.vts_vl_vdf,
    ctf.vts_pl_vdf,
    ctf.vts_gest,
    ctf.id_vts,
    ctf.obs_tmja,
    ctf.obs_pc_pl,
    ctf.obs_supl,
    ctf.id_sect,
    ctf.src_sect,
    ctf.autor_sect,
    ctf.obs_vts,
    ctf.vts_osm,
    ctf.vts_modif,
    ctf.vts_vl_f,
    ctf.vts_pl_f,
    ctf.vts_type_vl,
    ctf.vts_type_pl,
    ctf.src_vma,
    ctf.vma_vl,
    ctf.vma_pl,
    ctf.vma_type,
    ctf.codau_cont,
    ctf.id_codau_cont,
    ctf.tmja_cont,
    ctf.pc_pl_cont,
    ctf."source",
    ctf.target,
    ctf.cnt_src,
    ctf.cnt_tgt,
    ctf.imp_sup,
    ctf.imp_sup_src,
    ctf.imp_sup_tgt,
    ctf.recup,
    ctf.id_cnt2,
    ctf.id_struct_rout,
    ctf.id_sect_hom,
    ctf.attr_modif,
    ctf.id_bdc,
    ctf.geom,
    ctf.ang_orient_src_vert1,
    ctf.ang_orient_tgt_vert1,
    ctf.list_id_inter,
    ctf.nb_nod_non_topo,
    ctf.id_struct
from {{ref('mdl19_lin_upd_veh_km_' ~ dept)}} ctf
where ctf.coment_cpt = 'linearisation' and pl is not null
union
select 
    ctf.id_comptag,
    ctf.id_ign,
    ctf.id_simpli,
    ctf.id,
    ctf.nature,
    ctf.nom_coll_g,
    ctf.nom_coll_d,
    ctf.numero,
    ctf.importance,
    ctf.cl_admin,
    ctf.gestion,
    ctf.fictif,
    ctf.largeur,
    ctf.nb_voies,
    ctf.sens,
    ctf.etat,
    ctf.inseecom_g,
    ctf.inseecom_d,
    ctf.id_voie_g,
    ctf.id_voie_d,
    ctf.urbain,
    ctf.vit_moy_vl,
    ctf.restr_p,
    ctf.dept,
    ctf.dept_2024,
    ctf.dept_2023,
    ctf.long_km,
    ctf.src_cpt,
    ctf.coment_cpt,
    ctf.ann_pt,
    ctf.src_cpteur,
    ctf.coment_tmj,
    ctf.coment_tmj_f,
    ctf.ann_pc_pl,
    ctf.tmja,
    ctf.pc_pl,
    ctf.veh_km,
    ctf.tmja_final,
    ctf.pl,
    ctf.pl_final,
    ctf.pl_km,
    ctf.id_cpt1,
    ctf.id_cpt2,
    ctf.obs_tmj1,
    ctf.obs_tmj2,
    ctf.tmja_cpt1,
    ctf.tmja_cpt2,
    ctf.codau_cat,
    ctf.milieu,
    ctf.codau,
    ctf.type_vdf,
    ctf.vts_vl_vdf,
    ctf.vts_pl_vdf,
    ctf.vts_gest,
    ctf.id_vts,
    ctf.obs_tmja,
    ctf.obs_pc_pl,
    ctf.obs_supl,
    ctf.id_sect,
    ctf.src_sect,
    ctf.autor_sect,
    ctf.obs_vts,
    ctf.vts_osm,
    ctf.vts_modif,
    ctf.vts_vl_f,
    ctf.vts_pl_f,
    ctf.vts_type_vl,
    ctf.vts_type_pl,
    ctf.src_vma,
    ctf.vma_vl,
    ctf.vma_pl,
    ctf.vma_type,
    ctf.codau_cont,
    ctf.id_codau_cont,
    ctf.tmja_cont,
    ctf.pc_pl_cont,
    ctf."source",
    ctf.target,
    ctf.cnt_src,
    ctf.cnt_tgt,
    ctf.imp_sup,
    ctf.imp_sup_src,
    ctf.imp_sup_tgt,
    ctf.recup,
    ctf.id_cnt2,
    ctf.id_struct_rout,
    ctf.id_sect_hom,
    ctf.attr_modif,
    ctf.id_bdc,
    ctf.geom,
    ctf.ang_orient_src_vert1,
    ctf.ang_orient_tgt_vert1,
    ctf.list_id_inter,
    ctf.nb_nod_non_topo,
    ctf.id_struct
from {{ref('mdl19_lin_upd_veh_km_' ~ dept)}} ctf
where ctf.coment_cpt != 'linearisation' or ctf.coment_cpt is null or ctf.pl is null

{% endmacro %}