{% macro mcr_xx_maj_cmt_tmj_f_with_ids(model_src, dept=var('dept')) %}

-- Lignes présentes dans le seed (avec jointure)
select 
    -- Colonnes du seed
    ctf.id_comptag,
    ctf.id_ign,
    ctf.id_simpli,
    
    -- Toutes les autres colonnes du modèle
    ctf.id,
    ctf.nature,
    ctf.nom_coll_g,
    ctf.nom_coll_d,
    ctf.numero,
    ctf.importance,
    ctf.cl_admin,
    ctf.gestion,
    ctf.fictif,
    ctf.largeur,
    ctf.nb_voies,
    ctf.sens,
    ctf.etat,
    ctf.inseecom_g,
    ctf.inseecom_d,
    ctf.id_voie_g,
    ctf.id_voie_d,
    ctf.urbain,
    ctf.vit_moy_vl,
    ctf.restr_p,
    ctf.dept,
    ctf.dept_2024,
    ctf.dept_2023,
    ctf.long_km,
    ctf.src_cpt,
    ctf.coment_cpt,
    ctf.ann_pt,
    ctf.src_cpteur,
    uci.coment_tmj_f as coment_tmj,
    uci.coment_tmj_f,
    ctf.ann_pc_pl,
    ctf.tmja,
    ctf.pc_pl,
    ctf.veh_km,
    ctf.tmja_final,
    ctf.pl,
    ctf.pl_final,
    ctf.pl_km,
    ctf.id_cpt1,
    ctf.id_cpt2,
    ctf.obs_tmj1,
    ctf.obs_tmj2,
    ctf.tmja_cpt1,
    ctf.tmja_cpt2,
    ctf.codau_cat,
    ctf.milieu,
    ctf.codau,
    ctf.type_vdf,
    ctf.vts_vl_vdf,
    ctf.vts_pl_vdf,
    ctf.vts_gest,
    ctf.id_vts,
    ctf.obs_tmja,
    ctf.obs_pc_pl,
    ctf.obs_supl,
    ctf.id_sect,
    ctf.src_sect,
    ctf.autor_sect,
    ctf.obs_vts,
    ctf.vts_osm,
    ctf.vts_modif,
    ctf.vts_vl_f,
    ctf.vts_pl_f,
    ctf.vts_type_vl,
    ctf.vts_type_pl,
    ctf.src_vma,
    ctf.vma_vl,
    ctf.vma_pl,
    ctf.vma_type,
    ctf.codau_cont,
    ctf.id_codau_cont,
    ctf.tmja_cont,
    ctf.pc_pl_cont,
    ctf."source",
    ctf.target,
    ctf.cnt_src,
    ctf.cnt_tgt,
    ctf.imp_sup,
    ctf.imp_sup_src,
    ctf.imp_sup_tgt,
    ctf.recup,
    ctf.id_cnt2,
    ctf.id_struct_rout,
    ctf.id_sect_hom,
    ctf.attr_modif,
    ctf.id_bdc,
    ctf.geom,
    ctf.ang_orient_src_vert1,
    ctf.ang_orient_tgt_vert1,
    ctf.list_id_inter,
    ctf.nb_nod_non_topo,
    ctf.id_struct
from {{ ref('sed15a_dept' ~ dept ~ '_upd_cmt_tmj_f_with_ids') }} uci
join {{ model_src }} ctf
    on (array[ctf.id_ign]::text[] && uci.id_ign) or (ctf.id_simpli && uci.id_simpli)

UNION

-- Lignes de mdl1_creer_vue_19 non présentes dans le seed
select 
    ctf.id_comptag,
    ctf.id_ign,
    ctf.id_simpli,
    
    -- Toutes les autres colonnes du modèle
    ctf.id,
    ctf.nature,
    ctf.nom_coll_g,
    ctf.nom_coll_d,
    ctf.numero,
    ctf.importance,
    ctf.cl_admin,
    ctf.gestion,
    ctf.fictif,
    ctf.largeur,
    ctf.nb_voies,
    ctf.sens,
    ctf.etat,
    ctf.inseecom_g,
    ctf.inseecom_d,
    ctf.id_voie_g,
    ctf.id_voie_d,
    ctf.urbain,
    ctf.vit_moy_vl,
    ctf.restr_p,
    ctf.dept,
    ctf.dept_2024,
    ctf.dept_2023,
    ctf.long_km,
    ctf.src_cpt,
    ctf.coment_cpt,
    ctf.ann_pt,
    ctf.src_cpteur,
    ctf.coment_tmj,
    ctf.coment_tmj_f,
    ctf.ann_pc_pl,
    ctf.tmja,
    ctf.pc_pl,
    ctf.veh_km,
    ctf.tmja_final,
    ctf.pl,
    ctf.pl_final,
    ctf.pl_km,
    ctf.id_cpt1,
    ctf.id_cpt2,
    ctf.obs_tmj1,
    ctf.obs_tmj2,
    ctf.tmja_cpt1,
    ctf.tmja_cpt2,
    ctf.codau_cat,
    ctf.milieu,
    ctf.codau,
    ctf.type_vdf,
    ctf.vts_vl_vdf,
    ctf.vts_pl_vdf,
    ctf.vts_gest,
    ctf.id_vts,
    ctf.obs_tmja,
    ctf.obs_pc_pl,
    ctf.obs_supl,
    ctf.id_sect,
    ctf.src_sect,
    ctf.autor_sect,
    ctf.obs_vts,
    ctf.vts_osm,
    ctf.vts_modif,
    ctf.vts_vl_f,
    ctf.vts_pl_f,
    ctf.vts_type_vl,
    ctf.vts_type_pl,
    ctf.src_vma,
    ctf.vma_vl,
    ctf.vma_pl,
    ctf.vma_type,
    ctf.codau_cont,
    ctf.id_codau_cont,
    ctf.tmja_cont,
    ctf.pc_pl_cont,
    ctf."source",
    ctf.target,
    ctf.cnt_src,
    ctf.cnt_tgt,
    ctf.imp_sup,
    ctf.imp_sup_src,
    ctf.imp_sup_tgt,
    ctf.recup,
    ctf.id_cnt2,
    ctf.id_struct_rout,
    ctf.id_sect_hom,
    ctf.attr_modif,
    ctf.id_bdc,
    ctf.geom,
    ctf.ang_orient_src_vert1,
    ctf.ang_orient_tgt_vert1,
    ctf.list_id_inter,
    ctf.nb_nod_non_topo,
    ctf.id_struct
from {{ model_src }} ctf
where not exists (
    select 1 
    from {{ ref('sed15a_dept' ~ dept ~ '_upd_cmt_tmj_f_with_ids') }} uci
    where (array[ctf.id_ign]::text[] && uci.id_ign) or (ctf.id_simpli && uci.id_simpli)
)

{% endmacro %}