{% macro mcr_3b_maj_pt_linear_devenu_assoc_lin(annee=var('annee'), dept=var('dept')) %}
{% set annee_prec = annee | int - 1 %}

select 
    -- Colonnes de la vérification : récup de l'id_comptag de référence
    vpl.id_cpteur_ref id_comptag,
    -- Toutes les autres colonnes du modèle mdl1_creer_vue_19
    cv.id,
    cv.id_ign,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    'otv' src_cpt,
    'linearisation' coment_cpt,
    cv.ann_pt,
    cv.src_cpteur,
    cv.coment_tmj,
    cv.coment_tmj_f,
    cv.ann_pc_pl,
    cv.tmja,
    cv.pc_pl,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    cv.id_cpt1,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    cv.obs_tmja,
    cv.obs_pc_pl,
    case when cv.obs_supl is not null and cv.obs_supl like 'ex %' then 'ex '||cv.id_comptag||' traf{{annee_prec}},'||cv.obs_supl
		when cv.obs_supl is not null then 'ex '||cv.id_comptag||' traf{{annee_prec}},ex '||cv.obs_supl
		else 'ex '||cv.id_comptag||' traf{{annee_prec}}' end obs_supl,
    cv.id_sect,
    cv.src_sect,
    cv.autor_sect,
    cv.obs_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.id_simpli,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ref('mdl2h_lin_chk_pt_linear_absent_cptge_' ~ dept)}} vpl 
join {{ref('mdl1_creer_vue_' ~ dept)}} cv 
    on vpl.id_comptag = cv.id_comptag
UNION
-- Lignes de mdl1_creer_vue_19 non présentes dans la verif
select 
    cv.id_comptag,
    cv.id,
    cv.id_ign,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    cv.src_cpt,
    cv.coment_cpt,
    cv.ann_pt,
    cv.src_cpteur,
    cv.coment_tmj,
    cv.coment_tmj_f,
    cv.ann_pc_pl,
    cv.tmja,
    cv.pc_pl,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    cv.id_cpt1,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    cv.obs_tmja,
    cv.obs_pc_pl,
    cv.obs_supl,
    cv.id_sect,
    cv.src_sect,
    cv.autor_sect,
    cv.obs_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.id_simpli,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ref('mdl1_creer_vue_' ~ dept)}} cv
where not exists (
    select 1 
    from {{ref('mdl2h_lin_chk_pt_linear_absent_cptge_' ~ dept)}} vpl
    where vpl.id_comptag = cv.id_comptag)

{% endmacro %}