{% macro mcr_6_maj_auto_pt_non_linear_lin(annee=var('annee'), dept=var('dept'), sim_seuil_bas=0.2, dist_seuil_haut=20) %}

select 
    -- Colonnes de la vérification : récup de l'id_comptag de référence
    t2.id_comptag,
    -- Toutes les autres colonnes du modèle mdl3b_lin_upd_pt_linear_devenu_assoc_19
    t1.id,
    t1.id_ign,
    t1.nature,
    t1.nom_coll_g,
    t1.nom_coll_d,
    t1.numero,
    t1.importance,
    t1.cl_admin,
    t1.gestion,
    t1.fictif,
    t1.largeur,
    t1.nb_voies,
    t1.sens,
    t1.etat,
    t1.inseecom_g,
    t1.inseecom_d,
    t1.id_voie_g,
    t1.id_voie_d,
    t1.urbain,
    t1.vit_moy_vl,
    t1.restr_p,
    t1.dept,
    t1.dept_2024,
    t1.dept_2023,
    t1.long_km,
    'otv' src_cpt,
    'linearisation' coment_cpt,
    t1.ann_pt,
    t1.src_cpteur,
    t1.coment_tmj,
    t1.coment_tmj_f,
    t1.ann_pc_pl,
    t1.tmja,
    t1.pc_pl,
    t1.veh_km,
    t1.tmja_final,
    t1.pl,
    t1.pl_final,
    t1.pl_km,
    t1.id_cpt1,
    t1.id_cpt2,
    t1.obs_tmj1,
    t1.obs_tmj2,
    t1.tmja_cpt1,
    t1.tmja_cpt2,
    t1.codau_cat,
    t1.milieu,
    t1.codau,
    t1.type_vdf,
    t1.vts_vl_vdf,
    t1.vts_pl_vdf,
    t1.vts_gest,
    t1.id_vts,
    null obs_tmja,
    null obs_pc_pl,
    case when t1.obs_supl is not null then 'nouveau point traf{{annee}},ex '||t1.obs_supl
        else 'nouveau point traf{{annee}}' end obs_supl,
    t1.id_sect,
    t1.src_sect,
    t1.autor_sect,
    t1.obs_vts,
    t1.vts_osm,
    t1.vts_modif,
    t1.vts_vl_f,
    t1.vts_pl_f,
    t1.vts_type_vl,
    t1.vts_type_pl,
    t1.src_vma,
    t1.vma_vl,
    t1.vma_pl,
    t1.vma_type,
    t1.codau_cont,
    t1.id_codau_cont,
    t1.tmja_cont,
    t1.pc_pl_cont,
    t1."source",
    t1.target,
    t1.cnt_src,
    t1.cnt_tgt,
    t1.imp_sup,
    t1.imp_sup_src,
    t1.imp_sup_tgt,
    t1.recup,
    t1.id_cnt2,
    t1.id_struct_rout,
    t1.id_sect_hom,
    t1.id_simpli,
    t1.attr_modif,
    t1.id_bdc,
    t1.geom,
    t1.ang_orient_src_vert1,
    t1.ang_orient_tgt_vert1,
    t1.list_id_inter,
    t1.nb_nod_non_topo,
    t1.id_struct
from {{ref('cte1_mdl6_lin_upd_auto_pt_non_linear_' ~ dept ~ '__choix_cpt_tronc')}}  t2
join {{ref('mdl3b_lin_upd_pt_linear_devenu_assoc_'~dept)}} t1
    on t2.id_simpli = t1.id_simpli
where t1.coment_cpt = 'estimation' and t2.coment_cpt = 'estimation' 
        and t2.sim > {{sim_seuil_bas}} and t2.dist < {{dist_seuil_haut}}
UNION
-- Lignes de mdl3b_lin_upd_pt_linear_devenu_assoc_19 non présentes dans la maj
select 
    t1.id_comptag,
    t1.id,
    t1.id_ign,
    t1.nature,
    t1.nom_coll_g,
    t1.nom_coll_d,
    t1.numero,
    t1.importance,
    t1.cl_admin,
    t1.gestion,
    t1.fictif,
    t1.largeur,
    t1.nb_voies,
    t1.sens,
    t1.etat,
    t1.inseecom_g,
    t1.inseecom_d,
    t1.id_voie_g,
    t1.id_voie_d,
    t1.urbain,
    t1.vit_moy_vl,
    t1.restr_p,
    t1.dept,
    t1.dept_2024,
    t1.dept_2023,
    t1.long_km,
    t1.src_cpt,
    t1.coment_cpt,
    t1.ann_pt,
    t1.src_cpteur,
    t1.coment_tmj,
    t1.coment_tmj_f,
    t1.ann_pc_pl,
    t1.tmja,
    t1.pc_pl,
    t1.veh_km,
    t1.tmja_final,
    t1.pl,
    t1.pl_final,
    t1.pl_km,
    t1.id_cpt1,
    t1.id_cpt2,
    t1.obs_tmj1,
    t1.obs_tmj2,
    t1.tmja_cpt1,
    t1.tmja_cpt2,
    t1.codau_cat,
    t1.milieu,
    t1.codau,
    t1.type_vdf,
    t1.vts_vl_vdf,
    t1.vts_pl_vdf,
    t1.vts_gest,
    t1.id_vts,
    t1.obs_tmja,
    t1.obs_pc_pl,
    t1.obs_supl,
    t1.id_sect,
    t1.src_sect,
    t1.autor_sect,
    t1.obs_vts,
    t1.vts_osm,
    t1.vts_modif,
    t1.vts_vl_f,
    t1.vts_pl_f,
    t1.vts_type_vl,
    t1.vts_type_pl,
    t1.src_vma,
    t1.vma_vl,
    t1.vma_pl,
    t1.vma_type,
    t1.codau_cont,
    t1.id_codau_cont,
    t1.tmja_cont,
    t1.pc_pl_cont,
    t1."source",
    t1.target,
    t1.cnt_src,
    t1.cnt_tgt,
    t1.imp_sup,
    t1.imp_sup_src,
    t1.imp_sup_tgt,
    t1.recup,
    t1.id_cnt2,
    t1.id_struct_rout,
    t1.id_sect_hom,
    t1.id_simpli,
    t1.attr_modif,
    t1.id_bdc,
    t1.geom,
    t1.ang_orient_src_vert1,
    t1.ang_orient_tgt_vert1,
    t1.list_id_inter,
    t1.nb_nod_non_topo,
    t1.id_struct
from {{ref('mdl3b_lin_upd_pt_linear_devenu_assoc_'~dept)}} t1
where not exists (
    select 1 
    from {{ref('cte1_mdl6_lin_upd_auto_pt_non_linear_' ~ dept ~ '__choix_cpt_tronc')}} t2
    where (t2.id_simpli = t1.id_simpli) and (t1.coment_cpt = 'estimation' and t2.coment_cpt = 'estimation' 
        and t2.sim > 0.2 and t2.dist < 20))

{% endmacro %}