{% macro update_etirer_lin(dept=var('dept'), annee=var('annee')) %}

-- Lignes présentes dans le seed (avec jointure)
select 
    -- Colonnes du seed, avec fallback sur cv si null
    cv.id_comptag,
    cv.id_ign,
    cv.id_simpli,
    
    -- Toutes les autres colonnes du modèle
    cv.id,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    'otv' as src_cpt,
    'linearisation' as coment_cpt,
    cv.ann_pt,
    cv.coment_tmj,
    cv.coment_tmj_f,
    cv.ann_pc_pl,
    cv.tmja,
    cv.pc_pl,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    cv.id_cpt1,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    null as obs_tmja,
    null as obs_pc_pl,
    'linearisation etiree traf{{ annee }}' as obs_supl,
    cv.id_sect,
    cv.src_sect,
    cv.autor_sect,
    cv.obs_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ ref('dept' ~ dept ~ '_update_etire_linearisation') }} uel
join {{ ref('lin_update_oubli_linearisation_' ~ dept)}} cv
    on ((cv.id_ign = any(string_to_array(uel.id_ign, ';'))) or (cv.id_simpli[1] = any(string_to_array(uel.id_simpli, ';')::integer[])))

UNION

-- Lignes de lin_update_oubli_linearisation_19 non présentes dans le seed
select 
    cv.id_comptag,
    cv.id_ign,
    cv.id_simpli,
    
    -- Toutes les autres colonnes du modèle
    cv.id,
    cv.nature,
    cv.nom_coll_g,
    cv.nom_coll_d,
    cv.numero,
    cv.importance,
    cv.cl_admin,
    cv.gestion,
    cv.fictif,
    cv.largeur,
    cv.nb_voies,
    cv.sens,
    cv.etat,
    cv.inseecom_g,
    cv.inseecom_d,
    cv.id_voie_g,
    cv.id_voie_d,
    cv.urbain,
    cv.vit_moy_vl,
    cv.restr_p,
    cv.dept,
    cv.dept_2024,
    cv.dept_2023,
    cv.long_km,
    cv.src_cpt,
    cv.coment_cpt,
    cv.ann_pt,
    cv.coment_tmj,
    cv.coment_tmj_f,
    cv.ann_pc_pl,
    cv.tmja,
    cv.pc_pl,
    cv.veh_km,
    cv.tmja_final,
    cv.pl,
    cv.pl_final,
    cv.pl_km,
    cv.id_cpt1,
    cv.id_cpt2,
    cv.obs_tmj1,
    cv.obs_tmj2,
    cv.tmja_cpt1,
    cv.tmja_cpt2,
    cv.codau_cat,
    cv.milieu,
    cv.codau,
    cv.type_vdf,
    cv.vts_vl_vdf,
    cv.vts_pl_vdf,
    cv.vts_gest,
    cv.id_vts,
    cv.obs_tmja,
    cv.obs_pc_pl,
    cv.obs_supl,
    cv.id_sect,
    cv.src_sect,
    cv.autor_sect,
    cv.obs_vts,
    cv.vts_osm,
    cv.vts_modif,
    cv.vts_vl_f,
    cv.vts_pl_f,
    cv.vts_type_vl,
    cv.vts_type_pl,
    cv.src_vma,
    cv.vma_vl,
    cv.vma_pl,
    cv.vma_type,
    cv.codau_cont,
    cv.id_codau_cont,
    cv.tmja_cont,
    cv.pc_pl_cont,
    cv."source",
    cv.target,
    cv.cnt_src,
    cv.cnt_tgt,
    cv.imp_sup,
    cv.imp_sup_src,
    cv.imp_sup_tgt,
    cv.recup,
    cv.id_cnt2,
    cv.id_struct_rout,
    cv.id_sect_hom,
    cv.attr_modif,
    cv.id_bdc,
    cv.geom,
    cv.ang_orient_src_vert1,
    cv.ang_orient_tgt_vert1,
    cv.list_id_inter,
    cv.nb_nod_non_topo,
    cv.id_struct
from {{ ref('lin_update_oubli_linearisation_' ~ dept)}} cv
where not exists (
    select 1 
    from {{ ref('dept' ~ dept ~ '_update_etire_linearisation') }} uel
    where cv.id_ign = any(string_to_array(uel.id_ign, ';')) or cv.id_simpli[1] = any(string_to_array(uel.id_simpli, ';')::integer[])
)

{% endmacro %}