version: 2

sources:
  - name: traf
    description: > 
      Fichier de ligne BdTopo Thème transport 
    database: test_dbt  
    schema: lineaire  
    tables:
      - name: traf2024_bdt_na_ed24_l
        description: >
          Table des tronçons de route mars 2024 
          [troncon_de_route](https://data.geopf.fr/telechargement/download/BDTOPO/BDTOPO_3-3_TOUSTHEMES_GPKG_LAMB93_R75_2024-03-15/BDTOPO_3-3_TOUSTHEMES_GPKG_LAMB93_R75_2024-03-15.7z)
          Attention, dans le cadre du test dbt, cette doc donne un exemlpe, mais en réalité il y a tout un traitement pour transformer le fichier IGN vers 
          la table traf_2024
        columns:
          - name: id_comptag
            description: >
              Identifiant du compteur routier associé au tronçon de route, s'il y en a un.
              Permet de faire le lien entre la table des tronçons de route et la table des compteurs routiers.
      - name: traf2023_bdt_na_ed23_l
        description: >
          Table des tronçons de route mars ou septembre 2023 
          Attention, dans le cadre du test dbt, cette doc donne un exemlpe, mais en réalité il y a tout un traitement pour transformer le fichier IGN vers 
          la table traf_2023
        columns:
          - name: id_comptag
            description: >
              Identifiant du compteur routier associé au tronçon de route, s'il y en a un.
              Permet de faire le lien entre la table des tronçons de route et la table des compteurs routiers.
          
  - name: admi
    description: >
      Fichiers de surfaces BdTopo Thème administratif
    database: test_dbt  
    schema: aire  
    tables: 
      - name: dpt_bdt_na_ed24_s
        description: >
          Table des départements.
          mars 2024 
          [departement et commune](https://data.geopf.fr/telechargement/download/BDTOPO/BDTOPO_3-3_TOUSTHEMES_GPKG_LAMB93_R75_2024-03-15/BDTOPO_3-3_TOUSTHEMES_GPKG_LAMB93_R75_2024-03-15.7z)
          Décrit les départements et communes de Nouvelle-Aquitaine uniquement
      - name: com_bdt_na_ed24_s
        description: >
          Table des communes
          mars 2024 
          [departement et commune](https://data.geopf.fr/telechargement/download/BDTOPO/BDTOPO_3-3_TOUSTHEMES_GPKG_LAMB93_R75_2024-03-15/BDTOPO_3-3_TOUSTHEMES_GPKG_LAMB93_R75_2024-03-15.7z)
          Décrit les départements et communes de Nouvelle-Aquitaine uniquement

  - name: cptg
    description: >
      Ensemble des tables et vues décrivant les comptages routiers présents dans OTR.
      Contient les :
      - tables :
        - compteur, 
        - comptage, 
        - indic_agrege, 
      - vues :
        - 'vue_compteur_last_annee_know_tmja_pc_pl',
        - 'vue_evolutions_tmja'
      - table d'énumération :
        - enum_not_lin_why
    database: test_dbt
    schema: comptage
    tables:
      - name: compteur
        description: "Table des compteurs routiers, contient la géolocalisation"
      - name: comptage
        description: "Table des comptages réalisés sur les compteurs. 1 comptage par annéeet par compteur"
      - name: indic_agrege
        description: "Table des indicateurs agrégés issus des comptages, 1 ligne par comptage et indicateur"
      - name: vue_compteur_last_annee_know_tmja_pc_pl
        description: "Vue synthétique des compteurs avec la dernière année connue pour tmja, pc_pl"
      - name: vue_evolutions_tmja
        description: "Vue des évolutions annuelles du TMJA pour les compteurs ayant au moins 2 années de données"
      - name: enum_not_lin_why
        description: "Table d'énumération des raisons de non-linéarisation des comptages"

  - name: cptg_assoc
    description: >
      Ensemble des tables et vues décrivant les comptages associés à des comptages routiers de référence présents dans OTR.
      Contient les tables compteur, comptage, indic_agrege et la vue vue_assoc_compteur_last_annee_know_tmja_pc_pl.
    database: test_dbt
    schema: comptage_assoc
    tables:
      - name: compteur
        description: "Table des compteurs routiers, contient la géolocalisation"
        columns:
          - name: id_cpteur_asso
            description: "Identifiant du compteur associé"
          - name: id_cpteur_ref
            description: "Identifiant du compteur de référence auquel le compteur associé est lié"
      - name: comptage
        description: "Table des comptages réalisés sur les compteurs. 1 comptage par annéeet par compteur"
      - name: indic_agrege
        description: "Table des indicateurs agrégés issus des comptages, 1 ligne par comptage et indicateur"
      - name: vue_assoc_compteur_last_annee_know_tmja_pc_pl
        description: "Vue synthétique des compteurs avec la dernière année connue pour tmja, pc_pl"

  - name: ref
    description: >
      Fichiers de référentiels utilisés dans OTR
    database: test_dbt  
    schema: ref  
    tables:
      - name: bdt_na_2023_2024_l
        description: >
          Table de caractérisation des tronçons ayant subi des modifications de la part de l'IGN entre 2023 et 2024
        columns:
          - name: gid
            description: "Identifiant séquentiel automatique (serial4) interne"
          - name: id
            description: "Identifiant (int4)"
          - name: fid
            description: "Feature ID (int4)"
          - name: id_ign
            description: "Identifiant IGN (varchar(50))"
          - name: imp
            description: "Import (varchar(2))"
          - name: sup
            description: "Suppression (varchar(1))"
          - name: ad
            description: "Ajout/Suppression (varchar(1))"
          - name: id_propa
            description: "Identifiant propagation (varchar(50))"
          - name: propa
            description: "Propagation (varchar(20))"
          - name: pk_ign
            description: "PK IGN (varchar(1))"
          - name: obs
            description: "Observations (varchar(50))"
          - name: topo_n
            description: "Topologie N (varchar(1))"
          - name: o_1
            description: "O_L (int4)"
          - name: d_1
            description: "D_L (int4)"
          - name: recurs
            description: "V (varchar(1))"
          - name: o_2
            description: "G_2 (int4)"
          - name: d_2
            description: "D_2 (int4)"
          - name: mem_geom
            description: "Mémoire géométrie (varchar(1))"

      - name: pr_ed24_p
        description: >
          Table des points de repères linéaires BdTopo Thème transport
        columns:
          - name: fid
            description: "Identifiant séquentiel automatique (serial4)"
          - name: id
            description: "Identifiant (varchar(24))"
          - name: date_creat
            description: "Date de création (timestamptz)"
          - name: date_maj
            description: "Date de mise à jour (timestamptz)"
          - name: date_app
            description: "Date d'application (date)"
          - name: date_conf
            description: "Date de confirmation (date)"
          - name: source
            description: "Source (varchar)"
          - name: id_source
            description: "Identifiant source (varchar)"
          - name: route
            description: "Route (varchar(18))"
          - name: numero
            description: "Numéro (varchar(5))"
          - name: abscisse
            description: "Abscisse (int4)"
          - name: ordre
            description: "Ordre (float8)"
          - name: cote
            description: "Côté (varchar)"
          - name: statut
            description: "Statut (varchar)"
          - name: type_de_pr
            description: "Type de PR (varchar)"
          - name: libelle
            description: "Libellé (varchar)"
          - name: gestionnaire
            description: "Gestionnaire (varchar)"
          - name: insee_dep
            description: "Code INSEE département (varchar(3))"
          - name: id_route
            description: "Identifiant route (varchar(24))"
          - name: gestion
            description: "gestionnaire de la route (varchar)"

      - name: troncon_route_bdt_na_ed24_l
        description: >
          Table des tronçons de route BdTopo Thème transport
        
      - name: troncon_route_bdt_na_ed24_l_vertices_pgr
        description: >
          Table des sommets des tronçons de route BdTopo Thème transport pour pgRouting
          