version: 2

sources:
  - name: traf
    description: > 
      Fichier de ligne BdTopo Thème transport 
    database: test_dbt  
    schema: lineaire  
    tables:
      - name: traf2024_bdt_na_ed24_l
        description: >
          Table des tronçons de route mars 2024 
          [troncon_de_route](https://data.geopf.fr/telechargement/download/BDTOPO/BDTOPO_3-3_TOUSTHEMES_GPKG_LAMB93_R75_2024-03-15/BDTOPO_3-3_TOUSTHEMES_GPKG_LAMB93_R75_2024-03-15.7z)
          Attention, dans le cadre du test dbt, cette doc donne un exemlpe, mais en réalité il y a tout un traitement pour transformer le fichier IGN vers 
          la table traf_2024
      - name: traf2023_bdt_na_ed23_l
        description: >
          Table des tronçons de route mars ou septembre 2023 
          Attention, dans le cadre du test dbt, cette doc donne un exemlpe, mais en réalité il y a tout un traitement pour transformer le fichier IGN vers 
          la table traf_2023
  - name: admi
    description: >
      Fichiers de surfaces BdTopo Thème administratif
    database: test_dbt  
    schema: aire  
    tables: 
      - name: dpt_bdt_na_ed24_s
        description: >
          Table des départements.
          mars 2024 
          [departement et commune](https://data.geopf.fr/telechargement/download/BDTOPO/BDTOPO_3-3_TOUSTHEMES_GPKG_LAMB93_R75_2024-03-15/BDTOPO_3-3_TOUSTHEMES_GPKG_LAMB93_R75_2024-03-15.7z)
          Décrit les départements et communes de Nouvelle-Aquitaine uniquement
      - name: com_bdt_na_ed24_s
        description: >
          Table des communes
          mars 2024 
          [departement et commune](https://data.geopf.fr/telechargement/download/BDTOPO/BDTOPO_3-3_TOUSTHEMES_GPKG_LAMB93_R75_2024-03-15/BDTOPO_3-3_TOUSTHEMES_GPKG_LAMB93_R75_2024-03-15.7z)
          Décrit les départements et communes de Nouvelle-Aquitaine uniquement
  - name: cptg
    description: >
      Ensemble des tables et vues décrivant les comptages routiers présents dans OTR.
      Contient les tables compteur, comptage, indic_agrege et une vue 'vue_compteur_last_annee_know_tmja_pc_pl'.
    database: test_dbt
    schema: comptage
    tables:
      - name: compteur
        description: "Table des compteurs routiers, contient la géolocalisation"
      - name: comptage
        description: "Table des comptages réalisés sur les compteurs. 1 comptage par annéeet par compteur"
      - name: indic_agrege
        description: "Table des indicateurs agrégés issus des comptages, 1 ligne par comptage et indicateur"
      - name: vue_compteur_last_annee_know_tmja_pc_pl
        description: "Vue synthétique des compteurs avec la dernière année connue pour tmja, pc_pl"
